{
    'name': 'Character Tracker',
    'version': '1.0',
    'summary': 'Honkai: Star Rail - Character Tracker',
    'sequence': 1,
    'description': "",
    'depends': ['hsr_warp'],
    'data': [
        'views/hsr_team_menu_items.xml',
        'views/hsr_team_character_views.xml',
        'views/hsr_team_item_views.xml',
        'views/hsr_team_user_views.xml',
        'views/hsr_team_attribute_views.xml',
        'views/hsr_team_light_cone_views.xml',
        'views/hsr_team_relic_views.xml',

        'data/sr.relic.set.csv',
        'data/sr.character.template.csv',
        'security/ir.model.access.csv',
    ],
    'installable': True,
    'application': True,
    'icon': '/hsr_warp/static/description/icon(3).png',
    'pre_init_hook': 'pre_init',
    'assets': {},
    'license': 'LGPL-3',
}